package com.telesure.fwa;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class user implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "userName")
	private java.lang.String userName;

	public user() {
	}

	public java.lang.String getUserName() {
		return this.userName;
	}

	public void setUserName(java.lang.String userName) {
		this.userName = userName;
	}

	public user(java.lang.String userName) {
		this.userName = userName;
	}

}